//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedback.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_FormCreator_Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_FormCreator_Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("feedback.Resources.Views.FormCreator.Details", typeof(Views_FormCreator_Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال العاشر.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الحادي عشر.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثاني عشر.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثالث عشر.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الرابع عشر.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الخامس عشر.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقل من 25.
        /// </summary>
        internal static string answerAge1 {
            get {
                return ResourceManager.GetString("answerAge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 26 الى 35.
        /// </summary>
        internal static string answerAge2 {
            get {
                return ResourceManager.GetString("answerAge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 36 الى 46.
        /// </summary>
        internal static string answerAge3 {
            get {
                return ResourceManager.GetString("answerAge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعلى من 45.
        /// </summary>
        internal static string answerAge4 {
            get {
                return ResourceManager.GetString("answerAge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق بشدة.
        /// </summary>
        internal static string answerScale1 {
            get {
                return ResourceManager.GetString("answerScale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string answerScale2 {
            get {
                return ResourceManager.GetString("answerScale2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متأكد.
        /// </summary>
        internal static string answerScale3 {
            get {
                return ResourceManager.GetString("answerScale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق.
        /// </summary>
        internal static string answerScale4 {
            get {
                return ResourceManager.GetString("answerScale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق بشدة.
        /// </summary>
        internal static string answerScale5 {
            get {
                return ResourceManager.GetString("answerScale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدائي.
        /// </summary>
        internal static string asnwerEdu1 {
            get {
                return ResourceManager.GetString("asnwerEdu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        internal static string asnwerEdu2 {
            get {
                return ResourceManager.GetString("asnwerEdu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانوي.
        /// </summary>
        internal static string asnwerEdu3 {
            get {
                return ResourceManager.GetString("asnwerEdu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بكالوريوس.
        /// </summary>
        internal static string asnwerEdu4 {
            get {
                return ResourceManager.GetString("asnwerEdu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم عالي.
        /// </summary>
        internal static string asnwerEdu5 {
            get {
                return ResourceManager.GetString("asnwerEdu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string asnwerSex1 {
            get {
                return ResourceManager.GetString("asnwerSex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        internal static string asnwerSex2 {
            get {
                return ResourceManager.GetString("asnwerSex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثامن.
        /// </summary>
        internal static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الخامس.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الرابع.
        /// </summary>
        internal static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        internal static string labelName2 {
            get {
                return ResourceManager.GetString("labelName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل الدراسي.
        /// </summary>
        internal static string labelName3 {
            get {
                return ResourceManager.GetString("labelName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على القطاع الخاص المشاركة في رفع الوعي البيئي.
        /// </summary>
        internal static string labelName4 {
            get {
                return ResourceManager.GetString("labelName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهتمام المجتمع بالقضايا البيئية يساعد في زيادة الوعي البيئي.
        /// </summary>
        internal static string labelName5 {
            get {
                return ResourceManager.GetString("labelName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا أتردد في الإبلاغ عن أي سلوك ضار بالبيئة إلى الجهات المختصة.
        /// </summary>
        internal static string labelName6 {
            get {
                return ResourceManager.GetString("labelName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا أتردد في المشاركة في أي برنامج بيئي في مدينة ينبع الصناعية.
        /// </summary>
        internal static string labelName7 {
            get {
                return ResourceManager.GetString("labelName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهمني القضايا البيئية التي يتم طرحها من خلال وسائل الإعلام المختلفة.
        /// </summary>
        internal static string labelName8 {
            get {
                return ResourceManager.GetString("labelName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرامج التعليمية في المدارس تتميز بنطاق واسع لزيادة المعرفة البيئية لدى الطلبة
        ///.
        /// </summary>
        internal static string labelName9 {
            get {
                return ResourceManager.GetString("labelName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال التاسع.
        /// </summary>
        internal static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الأول :.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأسئلة.
        /// </summary>
        internal static string questionCount {
            get {
                return ResourceManager.GetString("questionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المشاركين.
        /// </summary>
        internal static string responseCount {
            get {
                return ResourceManager.GetString("responseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السابع.
        /// </summary>
        internal static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السادس.
        /// </summary>
        internal static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الإستبيان.
        /// </summary>
        internal static string surveydetails {
            get {
                return ResourceManager.GetString("surveydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثالث.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثاني.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
    }
}
