//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedback.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Form_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Form_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("feedback.Resources.Views.Form.Index", typeof(Views_Form_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقل من 25.
        /// </summary>
        internal static string AgeGroupLabel1 {
            get {
                return ResourceManager.GetString("AgeGroupLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 26 الى 35.
        /// </summary>
        internal static string AgeGroupLabel2 {
            get {
                return ResourceManager.GetString("AgeGroupLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 36 الى 46.
        /// </summary>
        internal static string AgeGroupLabel3 {
            get {
                return ResourceManager.GetString("AgeGroupLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعلى من 45.
        /// </summary>
        internal static string AgeGroupLabel4 {
            get {
                return ResourceManager.GetString("AgeGroupLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string before {
            get {
                return ResourceManager.GetString("before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدائي.
        /// </summary>
        internal static string eduLabel1 {
            get {
                return ResourceManager.GetString("eduLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        internal static string eduLabel2 {
            get {
                return ResourceManager.GetString("eduLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانوي.
        /// </summary>
        internal static string eduLabel3 {
            get {
                return ResourceManager.GetString("eduLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بكالوريوس.
        /// </summary>
        internal static string eduLabel4 {
            get {
                return ResourceManager.GetString("eduLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم عالي.
        /// </summary>
        internal static string eduLabel5 {
            get {
                return ResourceManager.GetString("eduLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوعي البيئي والاتجاهات.
        /// </summary>
        internal static string formSubSection2 {
            get {
                return ResourceManager.GetString("formSubSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاقتراحات والآراء حول المشاركة البيئية.
        /// </summary>
        internal static string formSubSection3 {
            get {
                return ResourceManager.GetString("formSubSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات شخصية.
        /// </summary>
        internal static string formSubSextion1 {
            get {
                return ResourceManager.GetString("formSubSextion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الوعي البيئي في مدينة ينبع الصناعية.
        /// </summary>
        internal static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة العمرية.
        /// </summary>
        internal static string labelName1 {
            get {
                return ResourceManager.GetString("labelName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحفاظ على البيئة مسؤولية الجميع.
        /// </summary>
        internal static string labelName10 {
            get {
                return ResourceManager.GetString("labelName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلوك الفرد تجاه البيئة يحدد مستوى الوعي البيئي.
        /// </summary>
        internal static string labelName11 {
            get {
                return ResourceManager.GetString("labelName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنشطة البيئية من القطاع الخاص في ينبع الصناعية محدودة.
        /// </summary>
        internal static string labelName12 {
            get {
                return ResourceManager.GetString("labelName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻣروﻧﺔ اﻛﺛر اﻟﺑﯾﺋﻲ اﻟﻌﻣل ﯾﺟﻌل ﺑﯾﺋﯾﺔ ﺟﻣﻌﯾﺔ واﻧﺷﺎء اﺳﺗﺣداث.
        /// </summary>
        internal static string labelName13 {
            get {
                return ResourceManager.GetString("labelName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات‏ ومقترحات ترغبون في ذكرها للمساهمة في زيادة اهتمام المجتمع في المحافظة على البيئة والمشاركة في الانشطة المصاحبة لها بمدينة ينبع الصناعية؟.
        /// </summary>
        internal static string labelName14 {
            get {
                return ResourceManager.GetString("labelName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        internal static string labelName2 {
            get {
                return ResourceManager.GetString("labelName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل الدراسي.
        /// </summary>
        internal static string labelName3 {
            get {
                return ResourceManager.GetString("labelName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على القطاع الخاص المشاركة في رفع الوعي البيئي.
        /// </summary>
        internal static string labelName4 {
            get {
                return ResourceManager.GetString("labelName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهتمام المجتمع بالقضايا البيئية يساعد في زيادة الوعي البيئي.
        /// </summary>
        internal static string labelName5 {
            get {
                return ResourceManager.GetString("labelName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا أتردد في الإبلاغ عن أي سلوك ضار بالبيئة إلى الجهات المختصة.
        /// </summary>
        internal static string labelName6 {
            get {
                return ResourceManager.GetString("labelName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا أتردد في المشاركة في أي برنامج بيئي في مدينة ينبع الصناعية..
        /// </summary>
        internal static string labelName7 {
            get {
                return ResourceManager.GetString("labelName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهمني القضايا البيئية التي يتم طرحها من خلال وسائل الإعلام المختلفة.
        /// </summary>
        internal static string labelName8 {
            get {
                return ResourceManager.GetString("labelName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرامج التعليمية في المدارس تتميز بنطاق واسع لزيادة المعرفة البيئية لدى الطلبة.
        /// </summary>
        internal static string labelName9 {
            get {
                return ResourceManager.GetString("labelName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string Sex1 {
            get {
                return ResourceManager.GetString("Sex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        internal static string Sex2 {
            get {
                return ResourceManager.GetString("Sex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صنـاعـــــــة وحيـــــــاة.
        /// </summary>
        internal static string slogen {
            get {
                return ResourceManager.GetString("slogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثالث.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثاني.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق بشدة.
        /// </summary>
        internal static string vote1 {
            get {
                return ResourceManager.GetString("vote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string vote2 {
            get {
                return ResourceManager.GetString("vote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متأكد.
        /// </summary>
        internal static string vote3 {
            get {
                return ResourceManager.GetString("vote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق.
        /// </summary>
        internal static string vote4 {
            get {
                return ResourceManager.GetString("vote4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق بشدة.
        /// </summary>
        internal static string vote5 {
            get {
                return ResourceManager.GetString("vote5", resourceCulture);
            }
        }
    }
}
