//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedback.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_FormCreator_Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_FormCreator_Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("feedback.Resources.Views.FormCreator.Create", typeof(Views_FormCreator_Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف سؤال.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقل من 25.
        /// </summary>
        internal static string AgeGroupLabel1 {
            get {
                return ResourceManager.GetString("AgeGroupLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 26 الى 35
        ///.
        /// </summary>
        internal static string AgeGroupLabel2 {
            get {
                return ResourceManager.GetString("AgeGroupLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من 36 الى 46
        ///.
        /// </summary>
        internal static string AgeGroupLabel3 {
            get {
                return ResourceManager.GetString("AgeGroupLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعلى من 45
        ///.
        /// </summary>
        internal static string AgeGroupLabel4 {
            get {
                return ResourceManager.GetString("AgeGroupLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجتمع.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدائي.
        /// </summary>
        internal static string eduLabel1 {
            get {
                return ResourceManager.GetString("eduLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        internal static string eduLabel2 {
            get {
                return ResourceManager.GetString("eduLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانوي.
        /// </summary>
        internal static string eduLabel3 {
            get {
                return ResourceManager.GetString("eduLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بكالوريوس.
        /// </summary>
        internal static string eduLabel4 {
            get {
                return ResourceManager.GetString("eduLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم عالي.
        /// </summary>
        internal static string eduLabel5 {
            get {
                return ResourceManager.GetString("eduLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الإستبيان.
        /// </summary>
        internal static string FromTitle {
            get {
                return ResourceManager.GetString("FromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص باللغة العربية.
        /// </summary>
        internal static string LanguageAr {
            get {
                return ResourceManager.GetString("LanguageAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص باللغة الإنجليزية.
        /// </summary>
        internal static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الأول.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال العاشر.
        /// </summary>
        internal static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الحادي عشر.
        /// </summary>
        internal static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثاني عشر.
        /// </summary>
        internal static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثالث عشر.
        /// </summary>
        internal static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الرابع عشر.
        /// </summary>
        internal static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الخامس عشر.
        /// </summary>
        internal static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثاني.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثالث.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الرابع.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الخامس.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السادس.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السابع.
        /// </summary>
        internal static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال الثامن.
        /// </summary>
        internal static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال التاسع.
        /// </summary>
        internal static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القسم الأول.
        /// </summary>
        internal static string SectionOneTitle {
            get {
                return ResourceManager.GetString("SectionOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القسم الثالث.
        /// </summary>
        internal static string SectionThreeTitle {
            get {
                return ResourceManager.GetString("SectionThreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القسم الثاني.
        /// </summary>
        internal static string SectionTwoTitle {
            get {
                return ResourceManager.GetString("SectionTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string Sex1 {
            get {
                return ResourceManager.GetString("Sex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        internal static string Sex2 {
            get {
                return ResourceManager.GetString("Sex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق بشدة
        ///.
        /// </summary>
        internal static string vote1 {
            get {
                return ResourceManager.GetString("vote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string vote2 {
            get {
                return ResourceManager.GetString("vote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متأكد
        ///.
        /// </summary>
        internal static string vote3 {
            get {
                return ResourceManager.GetString("vote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق
        ///.
        /// </summary>
        internal static string vote4 {
            get {
                return ResourceManager.GetString("vote4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موافق بشدة
        ///.
        /// </summary>
        internal static string vote5 {
            get {
                return ResourceManager.GetString("vote5", resourceCulture);
            }
        }
    }
}
